config/routes.rb
PlugInApp::Application.routes.draw do
  resources :users

  resources :lists

  resources :apartments
 get "sign_in" => 'sessions#new', :as => :sign_in
  get "/flights" => 'flights#index'

  post "sessions/create"

  get "sessions/destroy" => 'sessions#destroy', :as => :sign_out
 root to: 'apartments#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :comment, :apartment_id, :user_id
  validates_presence_of :apartment_id
  validates_presence_of :user_id
  validates_uniqueness_of :apartment_id
   belongs_to :apartment
  belongs_to :user
  def apart
  	@id=self.apartment_id
  	@apartment=Apartment.find_by_id(@id)
  	return @apartment
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new
    @apartment=params[:apt]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
<% @list.user_id=session[:user_id] %>
<% @list.apartment_id=@apartment %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id%>
    <br>
    <p><%= User.find(session[:user_id]).name %></p>
    <%= @apartment_id %>
    <br>
    <%= f.text_field :user_id %>  
  </div>
  <div class="field">

    <%= f.label :apartment_id %><br />
    <%= f.text_field :apartment_id %>
    
  </div>
  <div class="field" align="center" >
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  
  <div class="actions" align="center">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Listing Lists</h1>

<table>
  <tr>
    <th>User</th>
    <th>Apartment</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lists.each do |list| %>
  <tr>
    <td><%= list.user_id %></td>
    <td><%= list.apartment_id %></td>
    <td><%= list.comment %></td>
    <td><%= link_to 'Show', list %></td>
    <td><%= link_to 'Edit', edit_list_path(list) %></td>
    <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>User:</b>
  <%= @list.user_id %>
</p>

<p>
  <b>Apartment:</b>
  <%= @list.apartment_id %>
</p>

<p>
  <b>Comment:</b>
  <%= @list.comment %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', root_path %>