config/routes.rb
PlugInApp::Application.routes.draw do
  resources :users

  resources :lists

  resources :apartments
 get "sign_in" => 'sessions#new', :as => :sign_in
  get "/flights" => 'flights#index'

  post "sessions/create"

  get "sessions/destroy" => 'sessions#destroy', :as => :sign_out
 root to: 'apartments#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password

  has_secure_password

  validates_uniqueness_of :name
  validates_length_of :password, :minimum =>6 

  def num
  	@number=List.where(:user_id => self.id).count
  	return @number
  end
  def ownlist
  	@lists=List.where(:user_id => self.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authorize_user, :only => [:show, :edit, :update, :destroy]

  def authorize_user
    @user = User.find(params[:id])
    if @user.id != session[:user_id]
      redirect_to root_url, notice: "Nice Try"
    end
  end
   # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Password digest</th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
   <td><%= user.name %></td>
    <td><%= user.password_digest %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
 
<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Profile for : <%= @user.name %></h2>

<h2>Apartment Recorded: <%= @user.num %></h2>

<h2>Record History:</h2>
<% @lists=@user.ownlist %>
<table class="table table-hover">
      <thead>
        <tr>
          <th>Apartment ID</th>
          <th>Address</th>
          <th>City</th>
          <th>State</th>
          <th>ZipCode</th>
          <th>Neighborhood</th>
          <th>Comment</th>
        </tr>
      </thead>
      <tbody>
        <% @lists.each do |list| %>
        <% @apartment= list.apart %>
         
          <tr>
            <td><%= @apartment.id %></td>
            <td><%= @apartment.address %></td>
            <td><%= @apartment.city %></td>
            <td><%= @apartment.state %></td>
            <td><%= @apartment.zipcode %></td>
            <td><%= @apartment.neighborhood %></td>
            <td><%= list.comment %></td>
            <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'Add a new Apartment', new_apartment_path %>