config/routes.rb
PlugInApp::Application.routes.draw do
  resources :users

  resources :lists

  resources :apartments
 get "sign_in" => 'sessions#new', :as => :sign_in
  get "/flights" => 'flights#index'

  post "sessions/create"

  get "sessions/destroy" => 'sessions#destroy', :as => :sign_out
 root to: 'apartments#index'

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  # attr_accessible :title, :body
    attr_accessible :address, :city, :state, :zipcode, :neighborhood, :url
    def getNeighbor(zip)
        neig=HA[zip]
        self.neighborhood=neig
        puts neig
    end
    HA = {
60601 => "Loop", 
60602 => "Loop",
60603 => "Loop", 
60604 => "Loop", 
60605 => "Loop, Near South Side", 
60606 => "Loop, Near West Side",
60607 => "Loop, Near West Side, Near South Side", 
60608 => "Bridgeport, Lower West Side (Pilsen), McKinley Park, Near West Side, North Lawndale, South Lawndale" ,
60609 => "Armour Square, Bridgeport, Douglas, Fuller Park, Gage Park, Grand Boulevard, McKinley Park, New City, Washington Park" ,
60610 => "Near North Side, Near West Side", 
60611 => "Near North Side", 
60612 => "Near West Side, West Town", 
60613 => "Lakeview, North Center, Uptown", 
60614 => "Lincoln Park, Logan Square", 
60615 => "Grand Boulevard, Hyde Park, Kenwood, Washington Park", 
60616 => "Armour Square, Bridgeport, Douglas,Lower West Side (Pilsen), Near South Side", 
60617 => "Avalon Park, Calumet Heights, East Side, South Chicago, South Deering",
60618 => "Avondale, Irving Park, North Center", 
60619 => "Avalon Park, Burnside, Calumet Heights, Chatham, Greater Grand Crossing, Roseland, South Shore", 
60620 => "Auburn Gresham, Beverly, Chatham, Greater Grand Crossing, Roseland, Washington Heights", 
60621 => "Englewood, Greater Grand Crossing, Washington Park", 
60622 => "Humboldt Park, Logan Square, Near North Side, West Town", 
60623 => "North Lawndale, South Lawndale", 
60624 => "East Garfield Park, Humboldt Park, North Lawndale, West Garfield Park", 
60625 => "Albany Park, Lincoln Square, North Park", 
60626 => "Rogers Park", 
60627 => "Riverdale Chicago", 
60628 => "Pullman, Roseland, Washington Heights, West Pullman", 
60629 => "Chicago Lawn, Clearing, Gage Park, Garfield Ridge, West Elsdon, West Lawn", 
60630 => "Albany Park, Forest Glen, Irving Park, Jefferson Park, Portage Park", 
60631 => "Edison Park, Norwood Park", 
60632 => "Archer Heights, Brighton Park, Gage Park, Garfield Ridge, West Elsdon", 
60633 => "Hegewisch, South Deering", 
60634 => "Belmont Cragin, Dunning, Montclare, Portage Park", 
60635 => "Austin, Belmont Cragin, Dunning, Montclare", 
60636 => "Chicago Lawn, Gage Park, West Englewood", 
60637 => "Greater Grand Crossing, Hyde Park, South Shore, Washington Park, Woodlawn", 
60638 => "Clearing, Garfield Ridge", 
60639 => "Austin, Belmont Cragin, Hermosa, Humboldt Park, Logan Square", 
60640 => "Edgewater, Lincoln Square, Uptown", 
60641 => "Avondale, Belmont Cragin, Hermosa, Irving Park, Portage Park",
60642 => "Beverly", 
60643 => "Beverly, Morgan Park, Washington Heights, West Pullman", 
60644 => "Austin", 
60645 => "West Ridge", 
60646 => "Forest Glen, Jefferson Park, North Park, Norwood Park", 
60647 => "Hermosa, Humboldt Park, Logan Square, West Town", 
60649 => "South Shore", 
60651 => "Austin, Humboldt Park" ,
60652 => "Ashburn", 
60653 => "Douglas, Grand Boulevard, Kenwood, Oakland", 
60655 => "Beverly, Morgan Park, Mount Greenwood", 
60656 => "O Hare", 
60657 => "Lakeview, North Center", 
60659 => "North Park, West Ridge",
60660 => "Edgewater", 
60661 => "Loop, Near West Side", 
60664 => "Near West Side", 
60666 => "O Hare", 
60680 => "Near West Side", 
60681 => "Near West Side",
}
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all

    if params[:search].present?
      k = params[:search]
      @apartments = Apartment.where("neighborhood LIKE ?",
                                "%#{k}%")
    end
  end
  def show
    @apartment = Apartment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @apartment}
    end
  end
  def new
    @apartment = Apartment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @apartment }
    end
  end
  def create
    @apartment = Apartment.new(params[:apartment])
    @apartment.getNeighbor(@apartment.zipcode)
    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render json: @apartment, status: :created, location: @apartment }
      else
        format.html { render action: "new" }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end
  def edit
    @apartment = Apartment.find(params[:id])
  end
  def update
    @apartment = Apartment.find(params[:id])

    respond_to do |format|
      if @apartment.update_attributes(params[:user])
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @apartment = Apartment.find(params[:id])
    @apartment.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/views/apartments/_form.html.erb
<%= form_for(@apartment) do |f| %>
  <% if @apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <%



      777.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.number_field :zipcode %>
  </div>
  <!-- <div class="field">
    <%= f.label :neighborhood %><br />
    <%= f.text_field :neighborhood %>
  </div> -->
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form' %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', root_path %>

app/views/apartments/index.html.erb
<div class="row">
  <div class="span12">
    <h1 class="page-header">Apartments List</h1>
   
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Apartment ID</th>
          <th>Address</th>
          <th>City</th>
          <th>State</th>
          <th>ZipCode</th>
          <th>Neighborhood</th>
        </tr>
      </thead>
      <tbody>
        <% @apartments.each do |apartment| %>
          <tr>
            <td><%= apartment.id %></td>
            <td><%= apartment.address %></td>
            <td><%= apartment.city %></td>
            <td><%= apartment.state %></td>
            <td><%= apartment.zipcode %></td>
            <td><%= apartment.neighborhood %></td>
            <% if session[:user_id] %>
              <td><%= link_to 'Show Details', apartment_url(apartment.id) %></td>
              <td><%= link_to 'Delete', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% else %>
              <td>Sign Up!</td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Apartment ID:</b>
  <%= @apartment.id %>
</p>

<p>
  <b>Street:</b>
  <%= @apartment.address %>
</p>

<p>
  <b>City:</b>
  <%= @apartment.city %>
</p>
<p>
  <b>State:</b>
  <%= @apartment.state %>
</p>
<p>
  <b>Zipcode:</b>
  <%= @apartment.zipcode %>
</p>
<p>
  <b>Neighborhood:</b>
  <%= @apartment.neighborhood %>
</p>
<%= link_to 'Show the Website', @apartment.url %> |
<%= link_to "Add to List", {:controller =>'lists',     :action => 'new',:apt =>@apartment.id} %> |
<%= link_to 'Back', root_path %> |
<%= link_to 'Edit', edit_apartment_path %>
           