config/routes.rb
PlugInApp::Application.routes.draw do
  resources :users

  resources :lists

  resources :apartments
 get "sign_in" => 'sessions#new', :as => :sign_in
  get "/flights" => 'flights#index'

  post "sessions/create"

  get "sessions/destroy" => 'sessions#destroy', :as => :sign_out
 root to: 'apartments#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlugInApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="http://bootswatch.com/united/bootstrap.min.css">
  <style type="text/css">
    body { padding-top: 60px; padding-bottom: 40px; }
  </style>
  <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">

  <style type="text/css">
    .table thead th { font-size: 20px; background: #5484a7; color: white; text-align: center; height: 30px; padding: 12px; vertical-align: middle}
    .table td { text-align: center; }
  </style>
  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <link rel="apple-touch-icon" sizes="72x72" href="http://twitter.github.com/bootstrap/assets/images/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="http://twitter.github.com/bootstrap/assets/images/apple-touch-icon-114x114.png">

</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand span2" href="/">Plug In</a>
        <div class="nav-collapse">
          <form class="navbar-search pull-left" action="/apartments" method="get">
            <input type="text" class="search-query span3" placeholder="Search by Neighborhood" name="search">
          </form>
          <ul class="nav pull-right">
            

            <% if session[:user_id] %>
              <li><%= link_to "My Profile", user_url(session[:user_id]) %></li>
              <li><%= link_to "Sign Out", sign_out_url %></li>
            <% else %>
              <li><%= link_to "Sign Me Up!", new_user_url %></li>
              <li><%= link_to "Sign In", sign_in_url %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

  <div class="container">

    <%= notice %>
    <%= yield %>

    <hr>

  </div> <!-- /container -->

</body>
</html>